<?php

define('ROLE_ADMIN', 1);
define('ROLE_OPERATOR', 2);
define('ROLE_PENGURUS', 3);
define('ROLE_ANGGOTA', 4);

define('APPROVE_PENGAJUAN_PINJAMAN', 1);
define('REJECT_PENGAJUAN_PINJAMAN', 0);

define('COMPANY_SETTING_ADDRESS', 1);
