<?php

define('ROLE_ADMIN', 1);
define('ROLE_OPERATOR', 2);
define('ROLE_PENGURUS', 3);
define('ROLE_ANGGOTA', 4);

define('APPROVE_PENGAJUAN_PINJAMAN', 1);
define('REJECT_PENGAJUAN_PINJAMAN', 0);
define('CANCEL_PENGAJUAN_PINJAMAN', 2);
define('KONFIRMASI_PEMBAYARAN_PENGAJUAN_PINJAMAN', 3);

define('COMPANY_SETTING_ADDRESS', 1);
define('DEFAULT_BESAR_TABUNGAN', 0);

define('JENIS_SIMPANAN_POKOK', '411.01.000');
define('JENIS_SIMPANAN_WAJIB', '411.12.000');
define('JENIS_SIMPANAN_SUKARELA', '502.01.000');
define('JENIS_SIMPANAN_KHUSUS', '409.01.000');

define('TIPE_JENIS_PINJAMAN_DANA_KOPEGMAR', 1);
define('TIPE_JENIS_PINJAMAN_DANA_LAIN', 2);

define('KATEGORI_JENIS_PINJAMAN_JANGKA_PENDEK', 1);
define('KATEGORI_JENIS_PINJAMAN_JANGKA_PANJANG', 2);

define('JENIS_ANGGOTA_BIASA', 1);
define('JENIS_ANGGOTA_LUAR_BIASA', 2);
define('JENIS_ANGGOTA_PENSIUNAN', 3);

define('COMPANY_GROUP_KOPEGMAR', 1);
define('COMPANY_GROUP_KOJA', 2);

define('STATUS_PENGAJUAN_PINJAMAN_MENUNGGU_KONFIRMASI', 1);
define('STATUS_PENGAJUAN_PINJAMAN_MENUNGGU_PEMBAYARAN', 2);
define('STATUS_PENGAJUAN_PINJAMAN_DITERIMA', 3);
define('STATUS_PENGAJUAN_PINJAMAN_DITOLAK', 4);
define('STATUS_PENGAJUAN_PINJAMAN_DIBATALKAN', 5);

define('STATUS_PINJAMAN_BELUM_LUNAS', 1);
define('STATUS_PINJAMAN_LUNAS', 2);
